use parking_lot;
DESC ENTRY_EXIT_RECORD;
DESC USER;
SELECT * FROM ENTRY_EXIT_RECORD;
DROP TABLE ENTRY_EXIT_RECORD;

CREATE TABLE USER (
	VEHICLE_NUM VARCHAR(20) PRIMARY KEY,
    PW VARCHAR(50),
	FIRST_REG_DATE DATETIME,
	EXP_DATE DATETIME,
	TOTAL_FEE INT UNSIGNED
);

CREATE TABLE ENTRY_EXIT_RECORD(
	VEHICLE_NUM VARCHAR(20),
	ENTRY_DATE DATETIME,
	EXIT_DATE DATETIME,
	FEE SMALLINT UNSIGNED,
	CLASSIFICATION TINYINT DEFAULT 0,
	PRIMARY KEY(VEHICLE_NUM, ENTRY_DATE)
);

INSERT INTO ENTRY_EXIT_RECORD (VEHICLE_NUM, ENTRY_DATE, CLASSIFICATION) VALUES ('서울33자6323', '2025-04-17',0);